### ISSUE TITLE
Support for battery sensors created in yaml

### ISSUE THREAD

**Issue by stiltjack** [andrew-codechimp/HA-Battery-Notes#25]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

You seem to have based your integration on devices, which may not be created by yaml integrations. Wouldn't it be more logical to base it on sensors?

In my case the integration is for [Wireless Sensor Tags](https://www.home-assistant.io/integrations/wirelesstag/), which is set up in configuration.yaml. The integration creates battery sensors (data from the cloud) but there are no associated devices, so they do not appear in your configuration drop-down list.

### Describe the solution you'd like

The configuration drop-down list should contain **all** battery sensors.

### Describe alternatives you've considered

Can't see that there are any.

### Additional context

None.

**Comment by andrew-codechimp** [comment]
For an integration to add additional entities to an existing device it requires the unique ID to bind to so unfortunately I won't be able to support yaml based integrations.
Hopefully these will slowly disappear as maintainers move to UI based integrations.

It was a decision I made early on that batteries are related to a device rather than a sensor, from a user point of view they are expecting a device to have a battery and not chose a particular sensor, something like a motion sensor generally has a motion, light level and other sensors, it would be confusing as to which to add the battery type to.
