### ISSUE TITLE
Add the ability for custom devices

### ISSUE THREAD

**Issue by bat1939** [andrew-codechimp/HA-Battery-Notes#709]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I would like a way to track changing batteries for devices that do not show up in Home Assistant. Examples are TV remotes, Smoke Alarms, Kids Toys.

### Describe the solution you'd like

Be able to add a custom device and input the type of batteries required. Still have it auto generate the button sensor and the last changed sensor. 

### Describe alternatives you've considered

I know I can create the button sensor but not sure how to create/reference the last changed.

### Additional context

No additional context

**Comment by andrew-codechimp** [comment]
This isn't something I would want to include, Battery Notes relies on a device to be able to add the battery sensors to.  A totally uncontrolled device wouldn't have anything to associate with.

**Comment by magicus** [comment]
I came here because I had the same request. I'd like to add as a suggestion for other readers to do as I did: create a simple "dummy" entity using a Template helper (just have it return "Unavailable"), and then you have an entity you can attach your battery info to, to store battery type and last change date. Just remember that you will (of course) not get any automatic battery level readings...
