### ISSUE TITLE
Refactor batteries library to allow multiple definitions for model

### ISSUE THREAD

**Issue by codyc1515** [andrew-codechimp/HA-Battery-Notes#88]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The definitions library of batteries is blowing out in size. I observed that some of my devices are already in that file but were not auto-detected simply due to differences in how different integrations, i.e. ZHA vs. Zigbee2MQTT, present models and manufacturers.

### Describe the solution you'd like

Allow for one, or more, models and manufacturers against each key in the libraries definition file, e.g.

```
{
	"manufacturer": [
		"Xiaomi",
		"Aqara"
	],
	"model": [
		"Aqara human body movement and illuminance sensor (RTCGQ11LM)",
		"RTCGQ11LM"
	],
	"battery_type": "CR2450"
}
```

Or some similar format.

### Describe alternatives you've considered

We could simply keep adding to the database but it's going to grow larger and more unmanageable over time, especially so if there were to say be a dropdown selection of models in the future to maybe choose from.

### Additional context

.

**Comment by WendelFelius** [comment]
This would work for Philips and Signify Netherlands B.V. devices too.

**Comment by codyc1515** [comment]
Xiaomi and Aqara would be another similar pairing.

**Comment by andrew-codechimp** [comment]
This is something I've been thinking about as well but at the moment I'm not going to implement.

The library is under 30kb so no issues on performance yet.

The schema is complex enough for many to edit and I'm regularly adding missing commas, brackets etc. Adding array's will make my maintenance a lot harder.  The json validator catches things but I don't want to be hard and reject submissions as I want to grow the library rather than having people lose interest.

I may implement a GitHub Issues form to submit new devices, this wouldn't be able to handle arrays.

I may change my mind in future though :)
